### ISSUE TITLE
Select WASM Interpreter to support in Stage 2

### ISSUE THREAD

**Issue by akashin** [near/wasmtime#160]
Our main goal for Stage 2 is to generate a ZK circuit (ZKASM program) for a real WASM interpreter. This circuit should take a batch of independent WASM programs as an input and return a batch of their effects as an output.

We need to investigate what would make a WASM interpreter a good fit for this purpose and select concrete candidates that we will try to support.

Concretely, we need to understand:
- [ ] Which WASM features should the interpreter support
- [ ] Do we need `no_std` to achieve good binary size and performance?
- [ ] Does the interpreter need to have a good execution performance?

In the prior work (https://github.com/near/wasmtime/issues/28) we looked into:
- wain (https://github.com/rhysd/wain) - written in Rust
- wasmi (https://github.com/paritytech/wasmi/) - written in Rust
I think it's worth redoing the evaluation in the prior work.

**Comment by akashin** [comment]
I tried to compile [wasmi](https://github.com/paritytech/wasmi/)) interpreter using our benchmark framework: https://github.com/akashin/bench/blob/wasmi_interpreter/src/main.rs

The results so far:
- std version generated 293k lines of WAT; 726KB of WASM
- no_std version generated 231k lines of WAT; 573KB of WASM (I needed to implement global allocator for this to work, but there are only 4 calls to it in the interpreter)

The no_std version contains:
- A small number of f32 and f64 instructions
- 1200 functions
- 3 global variables
- 44k global data slots
- 183 indirect calls
- WASM tables and br_table instruction
- select instruction

It does not contain:
- `memory.fill` and `memory.grow` instructions
- popcnt instruction
- float sqrt, ceil, floor, etc.

I'll investigate next what is necessary to compile that version to ZKASM

**Comment by akashin** [comment]
I've compiled WASMI to ZKASM in https://github.com/near/wasmtime/pull/202. The resulting ZKASM file is 443k lines (from 231k lines of WASM). This seems manageable. Most importantly, we care about execution time of WASM programs on this interpreter rather than the size of the interpreter itself.

So far, there are only 5 missing instructions:
- Select
- BrTable
- CallInd
- fpromote
- fdemote

In total, the first 3 are called 1500 times: https://gist.github.com/akashin/88683dd08106ebdf0912172629365cae

The next steps are:
- Quickly check how hard would it be to implement those in case they are low-hanging fruits and we can get a working interpreter now
- Compile std-version of wasmi
- Select and compile another WASM interpreter for comparison

**Comment by akashin** [comment]
I'm working on `std` version support and it currently fails when executing the WAT file with the following error:
```rust
Err = Err(
    Error {
        context: "error while executing at wasm backtrace:\n    0: 0x5b3a7 - <unknown>!<wasm function 1125>\n    1: 0xc661 - <unknown>!<wasm function 148>\n    2: 0x66dc - <unknown>!<wasm function 34>\n    3: 0x71fd - <unknown>!<wasm function 53>",
        source: Error {
            context: "memory fault at wasm address 0x100000058 in linear memory of size 0x20000",
            source: MemoryOutOfBounds,
        },
    },
)
thread 'test_zkasm::tests::run_wat' panicked at cranelift/filetests/src/test_zkasm.rs:280:25:
```

The error is quite descriptive, but I can't find a place where we set the memory size to 0x20000.
From out code, the size of the heap should be 0x1_0000_0000: https://github.com/near/wasmtime/blob/41bb3255a24ba3b33708a9fdbdc0803ab9b12c78/cranelift/wasm/src/environ/zkasm.rs#L348

Will continue debugging this.

**Comment by akashin** [comment]
Some progress, this is not related to the ZKASM environment memory size, it's about running the WAT file using the Wasmtime engine. I was able to change the error message by setting
```rust
        let mut config = Config::default();
        config.static_memory_maximum_size(0);
        let engine = Engine::new(&config)?;
```

in https://github.com/near/wasmtime/blob/41bb3255a24ba3b33708a9fdbdc0803ab9b12c78/cranelift/filetests/src/test_zkasm.rs#L247

but it still fails with
```rust
Err = Err(
    Error {
        context: "error while executing at wasm backtrace:\n    0: 0x5b3a7 - <unknown>!<wasm function 1125>\n    1: 0xc661 - <unknown>!<wasm function 148>\n    2: 0x66dc - <unknown>!<wasm function 34>\n    3: 0x71fd - <unknown>!<wasm function 53>",
        source: MemoryOutOfBounds,
    },
)
```

I'm not that surprised, as the memory access at `0x100000058` is too large anyway for static memory, unless this is a virtual memory address.

**Comment by akashin** [comment]
I was able to confirm this error both with `wasmtime` and with `wasm-interp`:

Error from `wasm-interp`:
```sh
error initializing module: out of bounds memory access: access at 4294967384+8 >= max value 131072
```

Error from `wasmtime`:
```sh
Error: failed to run main module `compiled-wasm`

Caused by:
    0: failed to instantiate "compiled-wasm"
    1: error while executing at wasm backtrace:
           0: 0x5b3f6 - <unknown>!<wasm function 1126>
           1: 0xce50 - <unknown>!<wasm function 160>
           2: 0x66c2 - <unknown>!<wasm function 33>
           3: 0x71e8 - <unknown>!<wasm function 53>
           4: 0x71be - <unknown>!<wasm function 52>
    2: memory fault at wasm address 0x100000058 in linear memory of size 0x20000
    3: wasm trap: out of bounds memory access
```

So this has to do with the way we compile Rust to WASM. Will start tweaking the settings to fix this.

**Comment by akashin** [comment]
I was able to fix the problem by increasing the stack size:
```toml
[target.wasm32-unknown-unknown]
rustflags = [
  # "-C", "link-args=-z stack-size=2048",
  "-C", "link-args=-z stack-size=4096",
]
```

This should allow us to add WASMI as a benchmark to our codebase.

**Comment by akashin** [comment]
I've updated the benchmark https://github.com/near/wasmtime/pull/202/commits/cb687a384bdc9b2584b3047829a30943d12cd5e1 and now it fails with:

```rust
thread 'test_zkasm::tests::run_benchmarks' panicked at /Users/akashin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/ion/process.rs:1174:13:
assertion failed: lowest_cost_split_conflict_cost.is_some() ||
    lowest_cost_evict_conflict_cost.is_some()
```

This is a part of https://github.com/bytecodealliance/regalloc2, concretely this place: https://github.com/bytecodealliance/regalloc2/blob/ea86b8740f427a4e20f71e80727ff18985ae8f11/src/ion/process.rs#L1199

Looks like we'll need more detailed logs to debug this further.

**Comment by akashin** [comment]
I've also recently discovered a new tool `wasm-stats` and ran it on the resulting WASMI interpreter: https://gist.github.com/akashin/352793b47dc8ae1778261e4fc5312617

Here is the breakdown of top20 instructions:
```
Opcode counts:
local.get: 71492
i32.const: 48239
i32.add: 23429
local.set: 16986
end: 16427
i32.load: 15149
block: 13453
local.tee: 11128
i32.store: 10937
br_if: 10574
call: 9188
br: 7052
i32.eqz: 3272
i64.store: 3067
i32.load8_u: 2439
i64.load: 2373
i64.const: 2141
global.set: 1933
i32.shl: 1786
unreachable: 1628
```

It's also interesting to see the breakdown of operations with immediates:
```
Opcode counts with immediates:
i32.add: 23429
end: 16427
block: 13453
local.get 2: 12373
local.get 0: 12105
local.get 1: 12009
local.get 3: 9115
local.get 4: 7663
br_if 0: 6577
i32.load 2, 0: 5833
```

**Comment by akashin** [comment]
> I've updated the benchmark [cb687a3](https://github.com/near/wasmtime/commit/cb687a384bdc9b2584b3047829a30943d12cd5e1) and now it fails with:
> 
> ```rust
> thread 'test_zkasm::tests::run_benchmarks' panicked at /Users/akashin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/ion/process.rs:1174:13:
> assertion failed: lowest_cost_split_conflict_cost.is_some() ||
>     lowest_cost_evict_conflict_cost.is_some()
> ```
> 
> This is a part of https://github.com/bytecodealliance/regalloc2, concretely this place: https://github.com/bytecodealliance/regalloc2/blob/ea86b8740f427a4e20f71e80727ff18985ae8f11/src/ion/process.rs#L1199
> 
> Looks like we'll need more detailed logs to debug this further.

I was able to debug this by enabling `trace-log` feature on `regalloc2` crate and studying the logs just before the crash:
```
[2024-02-19T11:28:31Z TRACE regalloc2::ion::process] process_bundle: bundle LiveBundleIndex(9514) hint PReg(hw = 63, class = Int, index = 63)
[2024-02-19T11:28:31Z TRACE regalloc2::ion::requirement] compute_requirement: LiveBundleIndex(9514)
[2024-02-19T11:28:31Z TRACE regalloc2::ion::requirement]  -> LR LiveRangeIndex(12493): CodeRange { from: progpoint3119-post, to: progpoint3123-pre }
[2024-02-19T11:28:31Z TRACE regalloc2::ion::requirement]   -> use Use { operand: Def: v23180f reg, pos: progpoint3119-post, slot: 1, weight: 35828 }
[2024-02-19T11:28:31Z TRACE regalloc2::ion::requirement]      -> req Register
[2024-02-19T11:28:31Z TRACE regalloc2::ion::requirement]   -> use Use { operand: Use@Late: v23180f reg, pos: progpoint3122-post, slot: 1, weight: 35703 }
[2024-02-19T11:28:31Z TRACE regalloc2::ion::requirement]      -> req Register
[2024-02-19T11:28:31Z TRACE regalloc2::ion::requirement]  -> final: Register
[2024-02-19T11:28:31Z TRACE regalloc2::ion::process] attempt 1, req Register
[2024-02-19T11:28:31Z TRACE regalloc2::ion::process]  -> lowest cost evict: set None, cost None
[2024-02-19T11:28:31Z TRACE regalloc2::ion::process]  -> lowest cost split: cost None, point progpoint0-pre, reg PReg(hw = 63, class = Int, index = 63)
```

Concretely, the name of the register involved is `v23180f` which is a floating point register (see suffix `f`) which we have disabled in zkasm backend. By adding 1 floating point register, I get an error further down, which totally makes sense: `not implemented: Float reg saved in prologue`.

I've added [naive implementation](https://github.com/near/wasmtime/pull/202/commits/7984b2a895032bbd09ad4ce523e859a117a8a6cf) for floating points and the code now fails at:

```rust
thread 'test_zkasm::tests::run_benchmarks' panicked at cranelift/codegen/src/machinst/lower.rs:766:21:
should be implemented in ISLE: inst = `v10 = symbol_value.i64 gv0`, type = `Some(types::I64)`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm not sure what that error means, will investigate further.

**Comment by akashin** [comment]
Fixed the error above by defining the ISLE rule for `symbol_value`, a few errors later, got to another register allocation problem:

```asm
[2024-02-19T13:09:04Z ERROR cranelift_codegen::machinst::compile] Register allocation error for vcode
    VCode {
      Entry block: 0
      v194 := v192
      v195 := v193
      v196 := v204
      v197 := v196
    Block 0:
        (original IR block: block0)
        (successor: Block 1)
        (instruction range: 0 .. 7)
      Inst 0: args v192=A v193=B
      Inst 1: SUB v200,v199,v198
      Inst 2: srl v201,v194,v198
      Inst 3: sll v202,v194,v200
      Inst 4: select_reg v203,0,v202##condition=(v198 eq 0)
      Inst 5: OR v204,v201,v203
      Inst 6: j label1
    Block 1:
        (original IR block: block1)
        (instruction range: 7 .. 8)
      Inst 7:   :JMP(RR) v197=A
    }

    Error: SSA(VReg(vreg = 199, class = Int), Inst(1))
    CLIF for error:
    function u0:1430(i64, i64) -> i64 fast {
                                    block0(v0: i64, v1: i64):
    @8ce4a                              v3 = ireduce.i32 v0
    @8ce4d                              v4 = ireduce.i32 v1
    @8ce4e                              v5 = rotr v3, v4
    @8ce4f                              v6 = uextend.i64 v5
                                        v2 -> v6
    @8ce50                              jump block1

                                    block1:
    @8ce50                              return v2
    }

thread 'test_zkasm::tests::run_benchmarks' panicked at cranelift/codegen/src/machinst/compile.rs:76:14:
register allocation: SSA(VReg(vreg = 199, class = Int), Inst(1))
```

Maybe it has to do something with `select_reg` instruction?

**Comment by akashin** [comment]
I'm working through enabling necessary Float register support: https://github.com/near/wasmtime/pull/202/commits/6c1eb613f3ba15fef2446f1b14da841bd6f50c48

Right now it fails with another register allocation issue:
```rust
thread 'test_zkasm::tests::run_benchmarks' panicked at cranelift/codegen/src/machinst/compile.rs:76:14:
register allocation: SSA(VReg(vreg = 945, class = Float), Inst(407))
```

From the context, I see that Instruction 407 refers to "fsw" which corresponds to Storing f32:
```
Inst 404: AND v611,v609,v610
Inst 405: load_sym v608,userextname0+0
Inst 406: ADD v607,v557,v556
Inst 407: fsw v205,4(v558)
Inst 408: auipc v606,0; ld v606,12(v606); j 8; .4byte 0x3f
Inst 409: load_sym v605,userextname0+0
Inst 410: ADD v604,v563,v562
```

For some reason, vreg 945 is not defined, even though it is ought to be.

**Comment by akashin** [comment]
I fixed the previous problem by defining `fpromote` and `fdemote`. The next error is:

```rust
thread 'test_zkasm::tests::run_benchmarks' panicked at cranelift/codegen/src/machinst/compile.rs:76:14:
register allocation: SSA(VReg(vreg = 23180, class = Float), Inst(3123))
```

```
v7016 = load.f32 little heap v7015
v7017 = fpromote.f64 v7016
v7018 = uextend.i64 v92
v7019 = symbol_value.i64 gv1
v7020 = iadd v7019, v7018
store little heap v7017, v7020
```

```
Inst 3119: MLOAD f32 v23182,4(v6522)
Inst 3120: 0 => v23181  ;; LoadConst64
Inst 3121: load_sym v23179,userextname0+0
Inst 3122: ADD v23178,v6528,v6527
Inst 3123: MSTORE f64 v6526,0(v6529)
```

**Comment by akashin** [comment]
I was able to narrow down the problem to a simple CLIF function:
```clif
test compile precise-output
target zkasm-unknown-unknown

function u0:1(i32 vmctx) fast {
    block0(v0: i32):
        v1 = iconst.i64 4
        v2 = load.f32 little heap v1
        v3 = fpromote.f64 v2
        store little heap v3, v1
        jump block1

    block1:
        return
}
```

Now it fails with:

```
 ERROR cranelift_codegen::machinst::compile > Register allocation error for vcode
VCode {
  Entry block: 0
  v193 := v199
  v194 := v198
  v195 := v196
Block 0:
    (original IR block: block0)
    (successor: Block 1)
    (instruction range: 0 .. 6)
  Inst 0: args v192=A
  Inst 1: 4 => v199  ;; LoadConst64
  Inst 2: MLOAD f32 v198,0(v193)
  Inst 3: 0 => v197  ;; LoadConst64
  Inst 4: MSTORE f64 v195,0(v193)
  Inst 5: j label1
Block 1:
    (original IR block: block1)
    (instruction range: 6 .. 7)
  Inst 6:   :JMP(RR)
}

Error: SSA(VReg(vreg = 196, class = Float), Inst(4))
CLIF for error:
function u0:1(i32 vmctx) fast {
block0(v0: i32):
    v1 = iconst.i64 4
    v2 = load.f32 little heap v1  ; v1 = 4
    v3 = fpromote.f64 v2
    store little heap v3, v1  ; v1 = 4
    jump block1

block1:
    return
}

thread 'worker #2' panicked at cranelift/codegen/src/machinst/compile.rs:76:14:
register allocation: SSA(VReg(vreg = 196, class = Float), Inst(4))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

on this line in regalloc2: https://github.com/bytecodealliance/regalloc2/blob/ea86b8740f427a4e20f71e80727ff18985ae8f11/src/ssa.rs#L69
